# Generated by Django 2.2.1 on 2019-09-05 17:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XxgenAgenMaster',
            fields=[
                ('agen_id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('agent_name', models.CharField(blank=True, max_length=200, null=True)),
                ('agent_dob', models.DateField(blank=True, null=True)),
                ('agent_age', models.IntegerField(blank=True, null=True)),
                ('agent_qualification', models.CharField(blank=True, max_length=50, null=True)),
                ('agent_join_date', models.DateField(auto_now_add=True, null=True)),
                ('agent_start_date', models.DateField(blank=True, null=True)),
                ('agent_end_date', models.DateField(blank=True, null=True)),
                ('agent_status', models.CharField(blank=True, max_length=20, null=True)),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('last_update_date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='XxgenClaimsSurveyorMaster',
            fields=[
                ('surveyor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('surveyor_name', models.CharField(blank=True, max_length=200, null=True)),
                ('surveyor_qualificaition', models.CharField(blank=True, max_length=200, null=True)),
                ('surveyor_brach_code', models.CharField(blank=True, max_length=200, null=True)),
                ('surveyor_city', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.BigIntegerField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('last_update_date', models.DateField(blank=True, null=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='XxgenClaimStatusMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clm_status_code', models.CharField(max_length=200, unique=True)),
                ('clm_status_desc', models.CharField(blank=True, max_length=2000, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('last_update_date', models.DateField(blank=True, null=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='XxgenProductMaster',
            fields=[
                ('prod_code', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('prod_description', models.CharField(blank=True, max_length=2000, null=True)),
                ('prod_start_date', models.DateField(blank=True, null=True)),
                ('prod_end_date', models.DateField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=200, null=True)),
                ('last_update_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='XxgenVehicleDepriciation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_age_from', models.IntegerField(blank=True, null=True)),
                ('vehicle_age_to', models.IntegerField(blank=True, null=True)),
                ('dep_percent_on_idv', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('last_update_date', models.DateField(blank=True, null=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='XxgenVehicleMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mfg_company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('model_id', models.CharField(max_length=200, unique=True)),
                ('model_name', models.CharField(blank=True, max_length=200, null=True)),
                ('engine_cubic_capacity', models.CharField(blank=True, max_length=200, null=True)),
                ('insured_declared_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=200, null=True)),
                ('last_update_date', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='XxgenProductRiskMaster',
            fields=[
                ('risk_code', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('risk_description', models.CharField(blank=True, max_length=2000, null=True)),
                ('risk_premium_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('risk_start_date', models.DateField(blank=True, null=True)),
                ('risk_end_date', models.DateField(blank=True, null=True)),
                ('prem_calc_method', models.CharField(blank=True, max_length=200, null=True)),
                ('fixed_prem', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('fixed_si', models.BigIntegerField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=200, null=True)),
                ('last_update_date', models.DateField(blank=True, null=True)),
                ('prod_code', models.ForeignKey(blank=True, db_column='prod_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Masters.XxgenProductMaster')),
            ],
        ),
        migrations.CreateModel(
            name='XxgenNcbMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_years_from', models.BigIntegerField(blank=True, null=True)),
                ('no_years_to', models.BigIntegerField(blank=True, null=True)),
                ('discount_on_premium', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_desc', models.CharField(blank=True, max_length=2000, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('last_update_date', models.DateField(blank=True, null=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=200, null=True)),
                ('prod_code', models.ForeignKey(blank=True, db_column='prod_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Masters.XxgenProductMaster')),
            ],
        ),
        migrations.CreateModel(
            name='Xxgen_agent_Prod_Comm_Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comm_percent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=200, null=True)),
                ('last_update_date', models.DateField(blank=True, null=True)),
                ('agen_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Masters.XxgenAgenMaster')),
                ('prod_code', models.ForeignKey(blank=True, db_column='prod_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Masters.XxgenProductMaster')),
            ],
        ),
    ]
