# Generated by Django 2.2.1 on 2019-09-07 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xxgenvehiclemaster',
            name='model_id',
            field=models.CharField(max_length=200),
        ),
    ]
