# Generated by Django 2.2.1 on 2019-09-07 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0002_auto_20190907_0738'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='xxgenvehiclemaster',
            unique_together={('mfg_company_name', 'model_id', 'model_name')},
        ),
    ]
