# Generated by Django 2.2.1 on 2019-09-11 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UnderWriter', '__first__'),
        ('Masters', '0003_auto_20190907_0740'),
    ]

    operations = [
        migrations.CreateModel(
            name='XxgenClaims',
            fields=[
                ('claim_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('policy_no', models.BigIntegerField()),
                ('claim_date', models.DateField(blank=True, null=True)),
                ('claim_risk', models.CharField(blank=True, max_length=200, null=True)),
                ('amount_claimed', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('amount_setteled', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('date_of_settele', models.DateField(blank=True, null=True)),
                ('total_policy_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('total_claim_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('claim_status', models.CharField(blank=True, max_length=200, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('last_update_date', models.DateField(blank=True, null=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='XxgenClaimsSurveyorDtls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surveyor_name', models.CharField(blank=True, max_length=200, null=True)),
                ('clm_survey_status', models.CharField(blank=True, max_length=200, null=True)),
                ('surveyor_comments', models.CharField(blank=True, max_length=400, null=True)),
                ('surveyor_claim_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('last_update_date', models.DateField(blank=True, null=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=200, null=True)),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Claims.XxgenClaims')),
                ('surveyor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Masters.XxgenClaimsSurveyorMaster')),
            ],
        ),
        migrations.CreateModel(
            name='XxgenClaimsProcessDtls',
            fields=[
                ('clm_process_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('claim', models.BigIntegerField(max_length=99)),
                ('claim_date', models.DateField(blank=True, null=True)),
                ('amount_claimed', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('amount_setteled', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('date_of_settele', models.DateField(blank=True, null=True)),
                ('total_policy_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('total_claim_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('last_update_date', models.DateField(blank=True, null=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=200, null=True)),
                ('claim_status', models.ForeignKey(db_column='clm_status_code', default='SUBMITTED', on_delete=django.db.models.deletion.DO_NOTHING, to='Masters.XxgenClaimStatusMaster')),
                ('policy_no', models.ForeignKey(blank=True, db_column='policy_no', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='UnderWriter.XxgenPolicyDtls')),
            ],
        ),
        migrations.CreateModel(
            name='XxgenClaimsDocs',
            fields=[
                ('claim_doc_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('doc_type_code', models.CharField(blank=True, max_length=200, null=True)),
                ('doc_description', models.CharField(blank=True, max_length=2000, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('last_update_date', models.DateField(blank=True, null=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=200, null=True)),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Claims.XxgenClaims')),
            ],
        ),
    ]
