# Generated by Django 2.2.1 on 2019-09-11 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Claims', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xxgenclaimsprocessdtls',
            name='claim',
            field=models.IntegerField(),
        ),
    ]
