# Generated by Django 2.2.1 on 2019-09-11 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Claims', '0002_auto_20190911_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xxgenclaimsprocessdtls',
            name='claim_status',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
