# Generated by Django 2.2.1 on 2019-09-12 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Claims', '0003_auto_20190911_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xxgenclaimsprocessdtls',
            name='policy_no',
            field=models.IntegerField(),
        ),
    ]
