# Generated by Django 2.2.1 on 2019-09-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Claims', '0004_auto_20190912_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xxgenclaimssurveyordtls',
            name='surveyor_comments',
            field=models.TextField(),
        ),
    ]
