# Generated by Django 2.2.1 on 2019-09-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Claims', '0005_auto_20190912_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xxgenclaimsdocs',
            name='claim',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='xxgenclaimssurveyordtls',
            name='claim',
            field=models.BigIntegerField(),
        ),
    ]
