# Generated by Django 2.2.1 on 2019-09-12 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Claims', '0006_auto_20190912_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xxgenclaimssurveyordtls',
            name='surveyor_name',
        ),
        migrations.AlterField(
            model_name='xxgenclaimssurveyordtls',
            name='surveyor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Masters.XxgenClaimsSurveyorMaster'),
        ),
    ]
