# Generated by Django 2.2.1 on 2019-09-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Claims', '0007_auto_20190912_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xxgenclaimsdocs',
            name='claim_doc_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='xxgenclaimssurveyordtls',
            name='surveyor_comments',
            field=models.TextField(null=True),
        ),
    ]
