# Generated by Django 2.2.1 on 2019-09-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Claims', '0008_auto_20190912_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xxgenclaimssurveyordtls',
            name='claim',
            field=models.IntegerField(),
        ),
    ]
