# Generated by Django 2.2.1 on 2019-09-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Claims', '0009_auto_20190912_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='xxgenclaims',
            name='Remarks',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
