# Generated by Django 2.2.1 on 2019-09-12 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Claims', '0010_xxgenclaims_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='XxgenClaimsPayments',
            fields=[
                ('payment_receipt_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount_piad', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('date_of_piad', models.DateField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('last_update_date', models.DateField(blank=True, null=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=200, null=True)),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Claims.XxgenClaims')),
            ],
        ),
    ]
